# Generated by Django 4.1.5 on 2023-03-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contacts",
            name="phone",
            field=models.CharField(max_length=16),
        ),
    ]
